"use client";
import * as React from "react";
import { Globe2, Plus, CheckCircle2, Upload } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

const blank = { partnerAgencyName: "", country: "", foreignBrokerName: "", correspondentName: "", correspondentEmail: "", correspondentPhone: "" };
export default function ParceriasPage() {
  const [form, setForm] = React.useState(blank); const [files, setFiles] = React.useState<File[]>([]); const [state, setState] = React.useState<"idle"|"saving"|"ok"|"error">("idle");
  const set = (k: keyof typeof blank, v: string) => setForm({ ...form, [k]: v });
  async function save(e: React.FormEvent) { e.preventDefault(); setState("saving"); try { const sb=createClient(); const {data:{user}}=await sb.auth.getUser(); if(!user) throw new Error(); const documents:string[]=[]; for(const file of files){ const path=`${user.id}/partnerships/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`; const {error}=await sb.storage.from("partnership-documents").upload(path,file); if(error) throw error; documents.push(path); } const r=await fetch("/api/international/partnerships",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,documents})}); if(!r.ok) throw new Error(); setState("ok"); setForm(blank); setFiles([]); } catch { setState("error"); } }
  return <main className="mx-auto max-w-3xl p-6 sm:p-10"><p className="flex items-center gap-2 text-sm font-semibold text-primary"><Globe2 className="size-4"/> Internacional</p><h1 className="mt-2 font-display text-3xl">Nova parceria internacional</h1><p className="mt-2 text-sm text-muted-foreground">Regista o parceiro e o agente correspondente. Os documentos ficam privados e a parceria fica pendente de validação.</p><form onSubmit={save} className="mt-7 grid gap-4 rounded-3xl border bg-card p-5 sm:grid-cols-2"><Field label="Agência parceira" value={form.partnerAgencyName} onChange={v=>set("partnerAgencyName",v)}/><Field label="País" value={form.country} onChange={v=>set("country",v)}/><Field label="Broker no outro país" value={form.foreignBrokerName} onChange={v=>set("foreignBrokerName",v)}/><Field label="Agente correspondente" value={form.correspondentName} onChange={v=>set("correspondentName",v)}/><Field label="Email do correspondente" type="email" value={form.correspondentEmail} onChange={v=>set("correspondentEmail",v)}/><Field label="Telefone (opcional)" value={form.correspondentPhone} onChange={v=>set("correspondentPhone",v)}/><label className="sm:col-span-2 text-sm font-medium">Documentação da parceria<input required type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>setFiles(Array.from(e.target.files??[]))} className="mt-1.5 block w-full text-sm"/><span className="mt-1 flex items-center gap-1 text-xs font-normal text-muted-foreground"><Upload className="size-3"/>{files.length?`${files.length} ficheiro(s) pronto(s) a enviar`:"Contrato ou autorização de divulgação (PDF, Word ou imagem)"}</span></label><button className="sm:col-span-2 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground"><Plus className="size-4"/> {state === "saving" ? "A guardar…" : "Submeter parceria"}</button>{state === "ok" && <p className="sm:col-span-2 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 className="size-4"/> Parceria criada e enviada para validação.</p>}{state === "error" && <p className="sm:col-span-2 text-sm text-destructive">Não foi possível gravar. Confirme os campos e os documentos.</p>}</form></main>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}) { return <label className="text-sm font-medium">{label}<input required={label !== "Telefone (opcional)"} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border bg-transparent px-3 py-2.5 font-normal"/></label> }
