import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDownRight, ArrowRight, MapPin } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { SignatureLeadForm } from "@/components/signature/signature-lead-form";
import { SignatureTrack } from "@/components/signature/signature-track";
import { listSignatureProperties } from "@/lib/db/repo";
import { formatPrice } from "@/lib/format";

const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://housepro-chi.vercel.app";
export const metadata: Metadata={title:"HousePro Signature — Uma coleção rara",description:"Uma seleção privada das propriedades mais extraordinárias de Portugal.",alternates:{canonical:`${siteUrl}/signature`},openGraph:{title:"HousePro Signature",description:"Imóveis que não se repetem.",url:`${siteUrl}/signature`}};
const themes=["Junto ao mar","Património com história","Arquitetura contemporânea","Privacidade absoluta"];

export default async function SignaturePage({searchParams}:{searchParams:Promise<{tema?:string}>}){
 const properties=await listSignatureProperties(), theme=(await searchParams).tema, selected=(theme?properties.filter((p)=>p.signatureCollection===theme):properties).slice(0,9), hero=selected[0];
 return <div className="min-h-dvh bg-[#f3efe7] text-[#0a0a0a]"><SignatureTrack/><SiteHeader/><main>
  <section className="relative min-h-[620px] overflow-hidden bg-[#0a0a0a] text-[#f3efe7]">
   {hero?.image&&<img src={hero.signatureHeroUrl??hero.image} alt="" className="absolute inset-0 size-full object-cover opacity-55"/>}<div className="absolute inset-0 bg-[linear-gradient(100deg,rgba(10,10,10,.96),rgba(10,10,10,.58),rgba(10,10,10,.08))]"/>
   <div className="relative mx-auto flex min-h-[620px] max-w-7xl flex-col justify-end px-5 pb-12 pt-28 sm:px-8 lg:px-12"><p className="text-xs font-semibold tracking-[.25em] text-[#b99a5b]">HOUSEPRO <span className="font-serif tracking-[.35em]">SIGNATURE</span></p><p className="mt-10 text-xs tracking-[.22em] text-white/60">UMA COLEÇÃO RARA</p><h1 className="mt-4 max-w-3xl font-serif text-5xl leading-[.94] sm:text-7xl">Imóveis que não<br/>se repetem.</h1><p className="mt-6 max-w-md text-lg leading-8 text-white/75">Uma seleção privada das propriedades mais extraordinárias de Portugal.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#colecao" className="inline-flex min-h-12 items-center gap-2 bg-[#f3efe7] px-5 text-sm font-semibold text-[#0a0a0a]">Explorar a coleção <ArrowDownRight className="size-4"/></a><a href="#pedido" className="inline-flex min-h-12 items-center border border-white/35 px-5 text-sm font-semibold">Pedido privado</a></div></div>
  </section>
  <section id="colecao" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><p className="text-xs font-semibold tracking-[.2em] text-[#856a39]">SELEÇÃO SIGNATURE</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Propriedades escolhidas pelo que as torna únicas.</h2>
  {selected.length?<div className="mt-12 flex snap-x gap-5 overflow-x-auto pb-3 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-12">{selected.map((p,i)=><Link key={p.id} href={`/signature/${p.slug??p.id}`} className={`group min-w-[82%] snap-start overflow-hidden bg-[#151515] text-white sm:min-w-0 ${i===0?"sm:col-span-2 lg:col-span-5 lg:row-span-2":i===1?"sm:col-span-1 lg:col-span-3":i===2?"sm:col-span-1 lg:col-span-4":"sm:col-span-1 lg:col-span-4"}`}><div className={i===0?"aspect-[4/5]":i===1?"aspect-[16/10]":"aspect-[4/3]"}><img src={p.image} alt={p.title} className="size-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-5"><p className="text-[10px] font-semibold tracking-[.2em] text-[#c5a66c]">SIGNATURE</p><h3 className="mt-2 font-serif text-2xl">{p.signatureEditorialTitle??p.title}</h3><p className="mt-2 flex items-center gap-1 text-sm text-white/65"><MapPin className="size-3.5"/>{p.municipality}</p><p className="mt-4 text-sm">{p.signaturePriceVisible===false?"Preço sob consulta":formatPrice(p)}</p></div></Link>)}</div>:<div className="mt-12 border-y border-black/15 py-16"><p className="max-w-lg font-serif text-3xl">{theme?"Ainda não há imóveis publicados nesta seleção.":"A primeira coleção está a ser preparada."}</p><p className="mt-3 max-w-lg text-sm leading-6 text-black/65">Cada propriedade é analisada individualmente antes de poder integrar a HousePro Signature.</p></div>}</section>
  <section className="border-y border-black/10 bg-[#e9e3d8] px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold tracking-[.2em] text-[#856a39]">DESCOBRIR POR INSPIRAÇÃO</p><h2 className="mt-4 font-serif text-4xl">Quatro formas de viver o extraordinário.</h2><div className="mt-9 flex snap-x gap-3 overflow-x-auto pb-2"><Link href="/signature#colecao" className={`min-h-12 min-w-[150px] snap-start border border-black/15 px-5 py-4 text-sm font-medium ${!theme?"bg-black text-white":""}`}>Toda a coleção</Link>{themes.map(t=><Link key={t} href={`/signature?tema=${encodeURIComponent(t)}#colecao`} className={`min-h-12 min-w-[230px] snap-start border border-black/15 px-5 py-4 text-sm font-medium ${theme===t?"bg-black text-white":""}`}>{t}</Link>)}</div></div></section>
  <section id="pedido" className="bg-[#0a0a0a] px-5 py-20 text-[#f3efe7] sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold tracking-[.2em] text-[#b99a5b]">PESQUISA PRIVADA</p><h2 className="mt-4 font-serif text-5xl leading-tight">Não encontrou<br/>o que procura?</h2><p className="mt-5 max-w-md leading-7 text-white/70">Partilhe connosco o seu pedido. Procuramos dentro e fora do mercado.</p></div><SignatureLeadForm kind="private"/></div></section>
  <section className="bg-[#161616] px-5 py-20 text-[#f3efe7] sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-semibold tracking-[.2em] text-[#b99a5b]">CONSTRUÇÃO DE LUXO À MEDIDA</p><h2 className="mt-4 font-serif text-5xl leading-tight">Do terreno à casa irrepetível.</h2><p className="mt-5 max-w-xl leading-7 text-white/70">Arquitetura, construção e acompanhamento reunidos num serviço privado, prestado com parceiros técnicos aprovados.</p><ol className="mt-8 flex snap-x gap-3 overflow-x-auto text-sm">{["Terreno","Projeto","Licenciamento","Construção","Interiores e entrega"].map((s,i)=><li key={s} className="min-w-[130px] border-t border-[#b99a5b] pt-3"><span className="text-[#b99a5b]">0{i+1}</span><br/>{s}</li>)}</ol></div><SignatureLeadForm kind="build"/></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12"><div className="border border-black/15 p-7 sm:p-10"><p className="text-xs font-semibold tracking-[.2em] text-[#856a39]">APRESENTAR UM IMÓVEL</p><h2 className="mt-3 font-serif text-4xl">A sua propriedade merece ser analisada.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-black/65">A inclusão na coleção HousePro Signature está sempre sujeita a análise e aprovação editorial.</p><Link href="/signature/apresentar" className="mt-6 inline-flex min-h-11 items-center gap-2 border border-black px-5 text-sm font-semibold">Apresentar um imóvel <ArrowRight className="size-4"/></Link></div></section>
 </main><SiteFooter/></div>;
}
