"use client";
import * as React from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { track } from "@/lib/analytics";

type Kind = "private" | "build" | "present" | "property";
const labels: Record<Kind, string> = { private: "Signature — Pesquisa privada", build: "Signature — Construção por medida", present: "Signature — Candidatura de imóvel", property: "Signature — Imóvel" };
export function SignatureLeadForm({ kind, propertyId, compact = false }: { kind: Kind; propertyId?: string; compact?: boolean }) {
  const [state, setState] = React.useState<"idle"|"sending"|"ok"|"error">("idle");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); const f=new FormData(e.currentTarget); const payload={kind,propertyId,subSource:labels[kind],name:f.get("name"),email:f.get("email"),phone:f.get("phone"),details:f.get("details"),contactPreference:f.get("preference"),consent:f.get("consent")==="on",marketingConsent:f.get("marketing")==="on",pageUrl:location.href,utm:Object.fromEntries(new URLSearchParams(location.search).entries())}; const r=await fetch("/api/signature/lead",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); setState(r.ok?"ok":"error"); if(r.ok) track("signature_form_complete",{kind}); }
  if(state==="ok") return <p className="flex min-h-24 items-center gap-2 text-sm text-[#f3efe7]"><CheckCircle2 className="size-5 text-[#b99a5b]"/> Recebemos o seu pedido. Falamos consigo em privado.</p>;
  return <form onSubmit={submit} className="grid gap-3"><div className={compact?"grid gap-3":"grid gap-3 sm:grid-cols-2"}><input required name="name" placeholder="Nome" className="min-h-11 border-b border-white/25 bg-transparent px-1 text-sm text-white outline-none placeholder:text-white/55"/><input required type="email" name="email" placeholder="Email" className="min-h-11 border-b border-white/25 bg-transparent px-1 text-sm text-white outline-none placeholder:text-white/55"/>{!compact&&<><input name="phone" placeholder="Telefone" className="min-h-11 border-b border-white/25 bg-transparent px-1 text-sm text-white outline-none placeholder:text-white/55"/><select name="preference" className="min-h-11 border-b border-white/25 bg-transparent px-1 text-sm text-white"><option value="email">Preferência de contacto: email</option><option value="telefone">Telefone</option><option value="whatsapp">WhatsApp</option></select></>}</div><textarea required={!compact} name="details" placeholder={kind==="build"?"Localização, terreno, dimensão, estilo, orçamento e prazo":"Conte-nos o essencial da sua procura"} className="min-h-20 border-b border-white/25 bg-transparent px-1 py-2 text-sm text-white outline-none placeholder:text-white/55"/><label className="flex items-start gap-2 text-xs text-white/65"><input required name="consent" type="checkbox" className="mt-0.5"/> Autorizo o tratamento destes dados para resposta ao meu pedido.</label><label className="flex items-start gap-2 text-xs text-white/65"><input name="marketing" type="checkbox" className="mt-0.5"/> Aceito receber comunicações da HousePro (opcional).</label><button disabled={state==="sending"} className="mt-2 inline-flex min-h-11 items-center justify-center gap-2 border border-[#b99a5b] px-5 text-sm font-semibold text-[#f3efe7] transition hover:bg-[#b99a5b] hover:text-[#0a0a0a] disabled:opacity-60">{state==="sending"?"A enviar…":"Enviar pedido"}<ArrowRight className="size-4"/></button>{state==="error"&&<p className="text-sm text-red-200">Não foi possível enviar agora. Tente novamente.</p>}</form>;
}
