"use client";

import { useEffect, useState } from "react";

type Item = { id: string; reference: string; title: string; municipality: string; is_signature: boolean; signature_status: string; signature_order: number | null; signature_editorial_title: string | null; signature_collection: string | null; signature_visibility: string; signature_price_visible: boolean; signature_featured: boolean };
export function SignatureManager() {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/signature/manage").then((r) => r.ok ? r.json() : Promise.reject()).then((d) => setItems(d.properties ?? [])).catch(() => setError("Não foi possível carregar os imóveis.")).finally(() => setLoading(false)); }, []);
  async function save(item: Item) { setSaving(item.id); setError(""); const patch={ is_signature:item.is_signature, signature_status:item.signature_status, signature_order:item.signature_order, signature_editorial_title:item.signature_editorial_title, signature_collection:item.signature_collection, signature_visibility:item.signature_visibility, signature_price_visible:item.signature_price_visible, signature_featured:item.signature_featured }; const r=await fetch("/api/signature/manage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,patch})}); if(!r.ok)setError("Não foi possível guardar. Confirme as permissões e tente novamente."); setSaving(null); }
  function update(id:string, patch:Partial<Item>){setItems((all)=>all.map((item)=>item.id===id?{...item,...patch}:item));}
  if(loading)return <p className="mt-8 text-sm text-muted-foreground">A carregar coleção…</p>;
  return <div className="mt-8 space-y-4">{error&&<p className="text-sm text-destructive">{error}</p>}{items.map((item)=><article key={item.id} className="rounded-xl border bg-card p-4"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs text-muted-foreground">{item.reference} · {item.municipality}</p><h2 className="font-medium">{item.title}</h2></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.is_signature} onChange={(e)=>update(item.id,{is_signature:e.target.checked})}/> Candidato Signature</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">Estado<select value={item.signature_status} onChange={(e)=>update(item.id,{signature_status:e.target.value})} className="mt-1 min-h-10 w-full rounded border bg-background px-2"><option value="candidate">Candidato</option><option value="pending">Em análise</option><option value="approved">Aprovado</option><option value="rejected">Recusado</option></select></label><label className="text-xs">Visibilidade<select value={item.signature_visibility} onChange={(e)=>update(item.id,{signature_visibility:e.target.value})} className="mt-1 min-h-10 w-full rounded border bg-background px-2"><option value="private">Privado</option><option value="public">Público</option></select></label><label className="text-xs">Ordem<input type="number" value={item.signature_order??""} onChange={(e)=>update(item.id,{signature_order:e.target.value?Number(e.target.value):null})} className="mt-1 min-h-10 w-full rounded border bg-background px-2"/></label><label className="text-xs">Coleção<input value={item.signature_collection??""} onChange={(e)=>update(item.id,{signature_collection:e.target.value||null})} className="mt-1 min-h-10 w-full rounded border bg-background px-2"/></label></div><label className="mt-3 block text-xs">Título editorial<input value={item.signature_editorial_title??""} onChange={(e)=>update(item.id,{signature_editorial_title:e.target.value||null})} className="mt-1 min-h-10 w-full rounded border bg-background px-2"/></label><div className="mt-3 flex flex-wrap items-center gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={item.signature_price_visible} onChange={(e)=>update(item.id,{signature_price_visible:e.target.checked})}/> Mostrar preço</label><label className="flex items-center gap-2"><input type="checkbox" checked={item.signature_featured} onChange={(e)=>update(item.id,{signature_featured:e.target.checked})}/> Destacar na agregadora</label><button onClick={()=>save(item)} disabled={saving===item.id} className="ml-auto min-h-10 rounded bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-60">{saving===item.id?"A guardar…":"Guardar"}</button></div></article>)}</div>;
}
