"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { Override } from "@/lib/idealista/feed";

type Settings={customer_code:string;property_ids:string[];overrides:Record<string,Override>;development_service:boolean;enabled:boolean;review_approved:boolean;migration_confirmed:boolean;last_export_at:string|null;last_count:number;last_error:string|null;last_hash:string|null};
type Item={id:string;reference:string;title:string;legacyReference:string|null;area:number;beds:number;isDevelopment:boolean;eligible:boolean;excludedReason:string|null;problems:string[]};
type Report={config:Settings;ftpConfigured:boolean;count:number;schemaErrors:string[];problems:{reference:string;errors:string[]}[];listings:Item[]};
const input="mt-1 min-h-11 w-full rounded-lg border bg-background px-3 text-sm";
export function IdealistaIntegration() {
 const [report,setReport]=useState<Report|null>(null);const [config,setConfig]=useState<Settings|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/admin/idealista",{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error);setReport(body);setConfig(body.config);setDirty(false);}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.");}},[]);
 useEffect(()=>{void load();},[load]);
 function patch(value:Partial<Settings>){setConfig(c=>c?{...c,...value}:c);setDirty(true);setNotice("");}
 async function save(){if(!config)return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/admin/idealista",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(config)});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();setNotice("Configuração guardada e validada.");}catch(e){setError(e instanceof Error?e.message:"Falha ao guardar.");}finally{setBusy(false);}}
 function override(id:string,value:Partial<Override>){if(config)patch({overrides:{...config.overrides,[id]:{...config.overrides[id],...value}}});}
 if(!report || !config)return <section className="mt-6 rounded-2xl border bg-card p-6"><h2 className="font-display text-xl">Idealista · JSON V6</h2><p className="mt-3 text-sm">{error || "A carregar a integração…"}</p></section>;
 return <section className="mt-6 space-y-5 rounded-2xl border bg-card p-5 sm:p-7" aria-labelledby="idealista-heading">
  <div className="flex flex-wrap items-center justify-between gap-3"><h2 id="idealista-heading" className="font-display text-2xl">Idealista · JSON V6</h2><span className="rounded-full bg-secondary px-3 py-1 text-xs">{config.enabled?"Envio automático ativo":"Em preparação · envio desligado"}</span></div>
  <p className="text-sm leading-6 text-muted-foreground">Uma seleção completa por conta, verificada de 15 em 15 minutos. Só é transferida quando os dados mudam. Os anúncios reservados, com CPCV, vendidos, inativos, fora de mercado ou sem aprovação ficam excluídos.</p>
  <p className="text-xs text-muted-foreground">Descrições com títulos de idioma são separadas automaticamente e adaptadas ao limite de 4000 caracteres por idioma. O texto original mantém-se no imóvel.</p>
  <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Código ILC / chave para cargas<input value={config.customer_code} onChange={e=>patch({customer_code:e.target.value.trim()})} placeholder="ilc… (43 caracteres)" autoComplete="off" className={input}/><span className="mt-1 block text-xs text-muted-foreground">idealista → Configuração → Integrações → Chave para cargas</span></label><div className="rounded-xl bg-secondary/50 p-4 text-sm"><p>FTP: {report.ftpConfigured?"Configurado no servidor":"A aguardar os dados do idealista"}</p><p className="mt-2 text-xs text-muted-foreground">Os dados de acesso FTP são guardados nas variáveis privadas do servidor. A palavra-passe temporária da documentação não serve para enviar imóveis.</p></div></div>
  <div className="grid gap-3 text-sm"><label className="flex items-start gap-2"><input type="checkbox" checked={config.development_service} onChange={e=>patch({development_service:e.target.checked})} className="mt-1"/>A conta tem o serviço de empreendimentos ativo no idealista.</label><label className="flex items-start gap-2"><input type="checkbox" checked={config.review_approved} onChange={e=>patch({review_approved:e.target.checked})} className="mt-1"/>O idealista já reviu e aprovou o ficheiro de testes.</label><label className="flex items-start gap-2"><input type="checkbox" checked={config.migration_confirmed} onChange={e=>patch({migration_confirmed:e.target.checked})} className="mt-1"/>Confirmei as referências dos anúncios existentes com o idealista, ou não existem anúncios anteriores nesta conta.</label></div>
  <div className="border-t pt-5"><h3 className="font-medium">Imóveis desta conta</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Escolha todos os imóveis que pretende manter anunciados. Retirar um imóvel desta seleção desativa esse anúncio no próximo envio. Se retirar o último, contacte o idealista: um ficheiro vazio não remove todos os anúncios.</p><p className="mt-2 text-xs leading-5 text-muted-foreground">As referências antigas do CRM são sugeridas quando existem; confirme que correspondem às referências atuais no idealista para preservar o histórico.</p>
   <div className="mt-4 space-y-3">{report.listings.map(p=><article key={p.id} className="rounded-xl border p-4"><label className="flex items-start gap-3"><input type="checkbox" checked={config.property_ids.includes(p.id)} disabled={!p.eligible} onChange={e=>patch({property_ids:e.target.checked?[...config.property_ids,p.id]:config.property_ids.filter(id=>id!==p.id)})} className="mt-1"/><span><span className="block text-sm font-medium">{p.reference} · {p.title}</span><span className="mt-1 block text-xs text-muted-foreground">{p.isDevelopment?"Empreendimento":"Imóvel"}{p.excludedReason?` · ${p.excludedReason}`:""}</span></span></label><Link href={`/app/imovel/${p.id}/editar`} className="mt-2 inline-block text-xs text-primary underline">Consultar imóvel</Link>{p.eligible && config.property_ids.includes(p.id) && <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs">Referência no idealista<input value={config.overrides[p.id]?.reference??p.legacyReference??p.reference} onChange={e=>override(p.id,{reference:e.target.value})} maxLength={50} className={input}/></label><label className="text-xs">Área construída confirmada (m²)<input type="number" min="1" step="1" value={config.overrides[p.id]?.area??p.area??""} onChange={e=>override(p.id,{area:e.target.value?Number(e.target.value):undefined})} className={input}/></label><label className="text-xs">Quartos confirmados<input type="number" min="0" step="1" value={config.overrides[p.id]?.bedrooms??p.beds} onChange={e=>override(p.id,{bedrooms:e.target.value?Number(e.target.value):undefined})} className={input}/></label><details className="sm:col-span-3"><summary className="cursor-pointer text-xs text-muted-foreground">Migração de software: código externo antigo (apenas se indicado pelo idealista)</summary><input aria-label={`Código externo antigo de ${p.reference}`} value={config.overrides[p.id]?.propertyCode??""} disabled={Boolean(config.last_hash)} onChange={e=>override(p.id,{propertyCode:e.target.value})} placeholder={`Por defeito: ${p.id}`} maxLength={50} className={input}/></details></div>}{p.problems.length>0 && <p className="mt-3 text-xs text-amber-700">{p.problems.join(" · ")}{dirty?" · Guarde para validar os valores corrigidos.":""}</p>}</article>)}</div>
  </div>
  {report.problems.length>0 && !dirty && <div className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">Envio bloqueado: {report.problems.map(p=>`${p.reference}: ${p.errors.join(", ")}`).join("; ")}</div>}
  {report.schemaErrors.length>0 && config.customer_code && !dirty && <p className="text-sm text-destructive">A validação V6 encontrou erros. Confirme o ILC e os dados selecionados.</p>}
  <div className="border-t pt-4 text-sm"><p>Último envio FTP: {config.last_export_at?new Date(config.last_export_at).toLocaleString("pt-PT"):"Ainda não foi enviado nenhum ficheiro"}{config.last_export_at?` · ${config.last_count} anúncio(s)`:""}</p><p className="mt-1 text-xs text-muted-foreground">Transferência FTP não significa publicação aprovada. O idealista processa o ficheiro e envia o resultado da importação.</p>{config.last_error && <p className="mt-2 text-destructive">{config.last_error}</p>}</div>
  <label className="flex items-start gap-2 text-sm font-medium"><input type="checkbox" checked={config.enabled} onChange={e=>patch({enabled:e.target.checked})} className="mt-1"/>Ativar envio automático da seleção completa</label>
  {error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-sm text-green-700">{notice}</p>}
  <div className="flex flex-wrap items-center gap-3"><button disabled={busy} onClick={save} className="min-h-11 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy?"A guardar…":"Guardar e validar"}</button>{!dirty && report.count>0 && !report.problems.length && !report.schemaErrors.length && <a href="/api/admin/idealista?download=revisao" className="inline-flex min-h-11 items-center rounded-lg border px-4 text-sm">Descarregar JSON para revisão</a>}<span className="text-xs text-muted-foreground">{dirty?"Existem alterações por guardar.":`${report.count} anúncio(s) válido(s) na seleção.`}</span></div>
  {!config.customer_code && <p className="text-xs text-amber-700">Sem ILC, o download usa o código de exemplo da documentação e destina-se apenas à revisão técnica. Nunca é enviado automaticamente.</p>}
 </section>;
}
