"use client";
import * as React from "react";
import { CheckCircle2, RotateCcw, Save } from "lucide-react";
import { MediaUploadField } from "@/components/admin/media-upload-field";
import { mergePropertyHub, snapshotPropertyHub, type PropertyHubConfig } from "@/lib/data/property-hub";
import { publishSection } from "@/lib/data/site-content";

type AuditRow={name:string;currentAgency:string;nextAgency:string;winner:string;quality:number;priceMarket:number};
const municipalityKey=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export function PropertyHubAdmin({initial,municipalities,agencies,properties,audit}:{initial:PropertyHubConfig;municipalities:string[];agencies:{id:string;name:string}[];properties:{id:string;label:string}[];audit:AuditRow[]}){
 const [value,setValue]=React.useState(()=>mergePropertyHub(initial));const [status,setStatus]=React.useState("");
 const [pinProperty,setPinProperty]=React.useState("");const [pinStart,setPinStart]=React.useState("");const [pinEnd,setPinEnd]=React.useState("");
 const patch=(next:Partial<PropertyHubConfig>)=>setValue(v=>({...v,...next})); const promo=value.promo??{};
 async function save(){setStatus("A publicar…");const next={...value,versions:[{savedAt:new Date().toISOString(),snapshot:snapshotPropertyHub(value)},...(initial.versions??[])].slice(0,10)};const result=await publishSection("propertyhub",next);if(result.persisted)setValue(next);setStatus(result.persisted?"Publicado com sucesso.":`Falha: ${result.error||"não foi possível guardar"}`)}
 const toggleMunicipality=(name:string)=>{const current=value.municipalities??[];patch({municipalities:current.includes(name)?current.filter(n=>n!==name):[...current,name].slice(0,3)})};
 return <div className="mt-7 space-y-6"><section className="grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-2"><Field label="Título" value={value.title||""} change={title=>patch({title})}/><Field label="Introdução" value={value.intro||""} change={intro=>patch({intro})}/><Field label="Início da rotação" type="date" value={value.rotation?.startDate||""} change={startDate=>patch({rotation:{...value.rotation,startDate}})}/><div><p className="text-sm font-medium">Concelhos em destaque (máx. 3)</p><div className="mt-2 flex flex-wrap gap-2">{municipalities.map(name=><button key={name} onClick={()=>toggleMunicipality(name)} className={`rounded-full border px-3 py-2 text-xs ${(value.municipalities??[]).includes(name)?"bg-primary text-white":""}`}>{name}</button>)}</div></div></section>
 <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Ordem das agências</h2><p className="text-xs text-muted-foreground">Da mais antiga para a mais recente. Na ausência de ordem manual, é usada a ordem estável dos registos existentes.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{agencies.map((agency,index)=><label key={agency.id} className="flex items-center gap-3 rounded-xl border p-3"><span className="grid size-7 place-items-center rounded-full bg-secondary text-xs">{index+1}</span><span className="flex-1 text-sm">{agency.name}</span><input type="number" min="1" aria-label={`Posição de ${agency.name}`} className="w-16 rounded border p-2" value={Math.max(1,(value.rotation?.agencyOrder??agencies.map(a=>a.id)).indexOf(agency.id)+1)} onChange={e=>{const order=[...(value.rotation?.agencyOrder??agencies.map(a=>a.id))].filter(id=>id!==agency.id);order.splice(Math.max(0,Number(e.target.value)-1),0,agency.id);patch({rotation:{...value.rotation,agencyOrder:order}})}}/></label>)}</div></section>
 <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Destaque temporário de campanha</h2><p className="text-xs text-muted-foreground">Durante o intervalo, o imóvel substitui a rotação no respetivo concelho. No fim, a sequência diária retoma automaticamente.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm">Imóvel<select value={pinProperty} onChange={e=>setPinProperty(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="">Selecionar</option>{properties.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><Field label="Início" type="date" value={pinStart} change={setPinStart}/><Field label="Fim" type="date" value={pinEnd} change={setPinEnd}/></div><button type="button" disabled={!pinProperty||!pinStart||!pinEnd||pinEnd<pinStart} onClick={()=>{patch({rotation:{...value.rotation,pinned:[...(value.rotation?.pinned??[]),{propertyId:pinProperty,startsAt:pinStart,endsAt:pinEnd}]}});setPinProperty("");setPinStart("");setPinEnd("")} } className="mt-3 min-h-11 rounded-lg border px-4 text-sm font-semibold disabled:opacity-50">Fixar no intervalo</button>{(value.rotation?.pinned??[]).map((pin,index)=><div key={`${pin.propertyId}-${index}`} className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-secondary p-3 text-xs"><span>{properties.find(p=>p.id===pin.propertyId)?.label||pin.propertyId} · {pin.startsAt} — {pin.endsAt}</span><button onClick={()=>patch({rotation:{...value.rotation,pinned:value.rotation?.pinned?.filter((_,i)=>i!==index)}})} className="min-h-11 px-3 font-semibold text-destructive">Remover</button></div>)}</section>
 <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Fotografias dos concelhos</h2><p className="mb-4 text-xs text-muted-foreground">Apenas os três concelhos selecionados. Recomendado: 1200 × 900 px.</p><div className="grid gap-4">{(value.municipalities??[]).map(name=><MediaUploadField key={name} area="banners" label={name} help="JPG, PNG, WebP ou AVIF; máximo 25 MB." value={value.municipalityPhotos?.[municipalityKey(name)]} alt={value.municipalityAlt?.[municipalityKey(name)]} onUploaded={image=>patch({municipalityPhotos:{...(value.municipalityPhotos??{}),[municipalityKey(name)]:image}})} onAltChange={alt=>patch({municipalityAlt:{...(value.municipalityAlt??{}),[municipalityKey(name)]:alt}})}/>)}</div></section>
 <section className="grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-display text-xl">Banner promocional</h2><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={promo.active!==false} onChange={e=>patch({promo:{...promo,active:e.target.checked}})}/>Ativo</label></div><Field label="Título" value={promo.title||""} change={title=>patch({promo:{...promo,title}})}/><Field label="Texto" value={promo.text||""} change={text=>patch({promo:{...promo,text}})}/><Field label="Botão" value={promo.label||""} change={label=>patch({promo:{...promo,label}})}/><Field label="Ligação" value={promo.href||""} change={href=>patch({promo:{...promo,href}})}/><Field type="date" label="Início (opcional)" value={promo.startsAt||""} change={startsAt=>patch({promo:{...promo,startsAt}})}/><Field type="date" label="Fim (opcional)" value={promo.endsAt||""} change={endsAt=>patch({promo:{...promo,endsAt}})}/><div className="sm:col-span-2"><MediaUploadField area="banners" label="Fotografia do banner" help="Recomendado: 1800 × 700 px, JPG/PNG/WebP, máximo 25 MB." value={promo.image} alt={promo.alt} onUploaded={image=>patch({promo:{...promo,image}})} onAltChange={alt=>patch({promo:{...promo,alt}})}/></div></section>
 <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Pré-visualização</h2><div className="mt-3 grid grid-cols-3 gap-3"><Preview label="Mobile" width="max-w-[220px]"/><Preview label="Tablet" width="max-w-[420px]"/><Preview label="Desktop" width="max-w-full"/></div></section>
 <section className="rounded-2xl border bg-card p-5"><h2 className="font-display text-xl">Auditoria da rotação de hoje</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr className="border-b"><th className="p-2">Concelho</th><th>Agência atual</th><th>Próxima</th><th>Imóvel vencedor</th><th>Qualidade</th><th>Preço/mercado</th></tr></thead><tbody>{audit.map(row=><tr key={row.name} className="border-b"><td className="p-2 font-semibold">{row.name}</td><td>{row.currentAgency}</td><td>{row.nextAgency}</td><td>{row.winner}</td><td>{row.quality}%</td><td>{row.priceMarket}%</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Motivo: agência da posição diária; dentro dessa agência vence maior qualidade, depois melhor relação preço/mercado e, em empate, o anúncio mais antigo.</p></section>
 <div className="flex flex-wrap items-center gap-3"><button onClick={save} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-primary px-5 font-semibold text-white"><Save className="size-4"/>Publicar</button>{value.versions?.[0]&&<button onClick={()=>setValue(mergePropertyHub({...value.versions?.[0].snapshot,versions:value.versions?.slice(1)}))} className="inline-flex min-h-12 items-center gap-2 rounded-xl border px-5"><RotateCcw className="size-4"/>Repor versão de {new Date(value.versions[0].savedAt).toLocaleString("pt-PT")}</button>}{status&&<p role="status" className={status.startsWith("Falha")?"text-sm text-destructive":"flex items-center gap-1 text-sm text-emerald-700"}>{!status.startsWith("Falha")&&<CheckCircle2 className="size-4"/>}{status}</p>}</div></div>
}
function Field({label,value,change,type="text"}:{label:string;value:string;change:(v:string)=>void;type?:string}){return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={e=>change(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3 font-normal"/></label>}
function Preview({label,width}:{label:string;width:string}){return <div><p className="mb-2 text-xs font-medium">{label}</p><div className={`mx-auto aspect-[4/3] ${width} rounded-lg border bg-[#f4f7fb] p-2`}><div className="h-1/3 rounded bg-[#0D3B66]"/><div className="mt-2 h-2 w-2/3 rounded bg-slate-300"/><div className="mt-1 h-2 w-1/2 rounded bg-slate-200"/></div></div>}
