export const SIGNATURE_COLLECTIONS = [
  { slug: "junto-ao-mar", label: "Junto ao mar", title: "Uma vida ao ritmo do mar.", intro: "A luz que muda ao longo do dia. O horizonte que nunca termina. Lugares onde o oceano faz parte da casa.", storyTitle: "O horizonte como companhia.", story: "Da primeira luz à brisa ao fim da tarde, viver junto ao mar é escolher uma relação diferente com o tempo. Descubra a seleção Signature dedicada a propriedades com uma ligação especial à costa.", image: "/signature/editorial-coast-hero.webp", highlights: ["Luz e horizonte", "Uma ligação à costa", "Viver ao ar livre"] },
  { slug: "patrimonio-com-historia", label: "Património com história", title: "Casas que guardam o tempo.", intro: "Matérias, memórias e lugares com uma identidade que não se constrói de novo.", storyTitle: "Um novo capítulo numa história rara.", story: "Propriedades escolhidas pela sua identidade, carácter e relação com o lugar. Uma coleção para quem procura preservar o que torna uma casa irrepetível.", image: "/signature/editorial-construction.webp", highlights: ["Identidade e memória", "Matérias autênticas", "Carácter singular"] },
  { slug: "arquitetura-contemporanea", label: "Arquitetura contemporânea", title: "Uma outra forma de habitar.", intro: "Linhas pensadas. Luz natural. Espaços onde a arquitetura dá forma à experiência de viver.", storyTitle: "Quando o espaço faz a diferença.", story: "Uma seleção orientada pelo desenho, pela relação entre interior e exterior e pelo cuidado nos detalhes. Casas que traduzem uma visão contemporânea do conforto.", image: "/signature/editorial-construction.webp", highlights: ["Desenho e proporção", "Luz natural", "Dentro e fora"] },
  { slug: "privacidade-absoluta", label: "Privacidade absoluta", title: "O privilégio de ter espaço.", intro: "Silêncio, natureza e tempo para si. Propriedades onde o refúgio é parte da experiência.", storyTitle: "Mais espaço para o que importa.", story: "Lugares escolhidos pela reserva, pelos espaços exteriores e pela possibilidade de viver com tranquilidade. Uma coleção dedicada a quem procura um refúgio próprio.", image: "/signature/editorial-coast-hero.webp", highlights: ["Reserva e tranquilidade", "Espaços exteriores", "Um refúgio pessoal"] },
] as const;
export type SignatureCollectionSlug = typeof SIGNATURE_COLLECTIONS[number]["slug"];
export function getSignatureCollection(value?: string | null) {
  if (!value?.trim()) return undefined;
  const normalized = value.trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/\s+/g, "-");
  return SIGNATURE_COLLECTIONS.find(c => c.slug === normalized);
}
