"use client";
import * as React from "react";
import { Building2, Plus, CheckCircle2 } from "lucide-react";
export default function GestaoEmpreendimentos() {
  const [d,setD]=React.useState({name:"",municipality:"",parish:"",summary:"",description:"",stage:"planta",units:[{title:"",typology:"",price:"",area:""}]}); const [state,setState]=React.useState("idle");
  const patch=(p: Partial<typeof d>)=>setD({...d,...p}); const unit=(i:number,p:Partial<typeof d.units[number]>)=>patch({units:d.units.map((u,j)=>j===i?{...u,...p}:u)});
  async function save(e:React.FormEvent){e.preventDefault();setState("saving");const r=await fetch("/api/developments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(d)});setState(r.ok?"ok":"error")}
  return <main className="mx-auto max-w-3xl p-6 sm:p-10"><p className="flex items-center gap-2 text-sm font-semibold text-primary"><Building2 className="size-4"/> Empreendimentos</p><h1 className="mt-2 font-display text-3xl">Novo empreendimento</h1><p className="mt-2 text-sm text-muted-foreground">É a ficha-mãe do projeto. As unidades ficam associadas e todas as leads serão entregues a ti enquanto responsável.</p><form onSubmit={save} className="mt-7 space-y-5 rounded-3xl border bg-card p-5"><div className="grid gap-4 sm:grid-cols-2"><F label="Nome" value={d.name} onChange={v=>patch({name:v})}/><F label="Concelho" value={d.municipality} onChange={v=>patch({municipality:v})}/><F label="Freguesia" value={d.parish} onChange={v=>patch({parish:v})}/><label className="text-sm font-medium">Fase<select value={d.stage} onChange={e=>patch({stage:e.target.value})} className="mt-1.5 w-full rounded-xl border bg-transparent px-3 py-2.5"><option value="planta">Em planta</option><option value="construcao">Em construção</option><option value="pronto">Pronto</option></select></label></div><label className="block text-sm font-medium">Resumo<textarea value={d.summary} onChange={e=>patch({summary:e.target.value})} className="mt-1.5 min-h-20 w-full rounded-xl border bg-transparent p-3 font-normal"/></label><div><p className="font-medium">Unidades iniciais</p>{d.units.map((u,i)=><div key={i} className="mt-2 grid gap-2 sm:grid-cols-4"><input placeholder="Ex.: Bloco A · 2.º Dto" value={u.title} onChange={e=>unit(i,{title:e.target.value})} className="rounded-lg border p-2 text-sm"/><input placeholder="T2" value={u.typology} onChange={e=>unit(i,{typology:e.target.value})} className="rounded-lg border p-2 text-sm"/><input placeholder="Preço" value={u.price} onChange={e=>unit(i,{price:e.target.value})} className="rounded-lg border p-2 text-sm"/><input placeholder="m²" value={u.area} onChange={e=>unit(i,{area:e.target.value})} className="rounded-lg border p-2 text-sm"/></div>)}<button type="button" onClick={()=>patch({units:[...d.units,{title:"",typology:"",price:"",area:""}]})} className="mt-3 inline-flex items-center gap-1 text-sm text-primary"><Plus className="size-4"/> Adicionar unidade</button></div><button className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground">{state==="saving"?"A guardar…":"Criar empreendimento"}</button>{state==="ok"&&<p className="flex gap-2 text-sm text-emerald-700"><CheckCircle2 className="size-4"/> Empreendimento criado.</p>}{state==="error"&&<p className="text-sm text-destructive">Não foi possível criar.</p>}</form></main>
}
function F({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-medium">{label}<input required={label==="Nome"} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border bg-transparent px-3 py-2.5 font-normal"/></label>}
