"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { ArrowRight, Bath, Bell, BedDouble, ChevronDown, Grid2X2, ListFilter, Map as MapIcon, MapPin, Maximize2, Search, SlidersHorizontal, X } from "lucide-react";
import type { Property } from "@/lib/data/types";
import type { PropertyHubConfig } from "@/lib/data/property-hub";
import { mergePropertyHub } from "@/lib/data/property-hub";
import { propertyScores, selectGeneralHero, selectMunicipalityWinner } from "@/lib/data/property-discovery";
import { formatPrice } from "@/lib/format";
import { FavoriteButton } from "@/components/property/favorite-button";
import { track } from "@/lib/analytics";

const Map = MapIcon;

type Filters = { operacao:string;q:string;concelho:string;freguesia:string;tipo:string;tipologia:string;precoMin:string;precoMax:string;quartos:string;banhos:string;areaMin:string;caracteristica:string;referencia:string;signature:string;empreendimento:string;estado:string;ordem:string };
const KEYS:(keyof Filters)[]=["operacao","q","concelho","freguesia","tipo","tipologia","precoMin","precoMax","quartos","banhos","areaMin","caracteristica","referencia","signature","empreendimento","estado","ordem"];
const readFilters=(sp:URLSearchParams)=>Object.fromEntries(KEYS.map(k=>[k,sp.get(k)||(k==="q"?sp.get("local")||"":k==="ordem"?"recentes":"")])) as Filters;
const clean=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();

export function PropertyDiscovery({properties,config:source}:{properties:Property[];config:PropertyHubConfig}){
 const config=React.useMemo(()=>mergePropertyHub(source),[source]); const sp=useSearchParams(); const router=useRouter(); const pathname=usePathname();
 const [filters,setFilters]=React.useState(()=>readFilters(sp)); const [advanced,setAdvanced]=React.useState(false); const [view,setView]=React.useState<"grid"|"map">("grid"); const [visible,setVisible]=React.useState(4); const [alertOpen,setAlertOpen]=React.useState(false);
 React.useEffect(()=>{const y=Number(sessionStorage.getItem(`hp-scroll:${location.pathname}${location.search}`));if(y)requestAnimationFrame(()=>scrollTo({top:y}));track("property_hub_view")},[]);
 React.useEffect(()=>setFilters(readFilters(sp)),[sp]);
 const remember=()=>sessionStorage.setItem(`hp-scroll:${location.pathname}${location.search}`,String(scrollY));
 const apply=React.useCallback((next=filters)=>{const params=new URLSearchParams();KEYS.forEach(k=>{if(next[k]&&!(k==="ordem"&&next[k]==="recentes"))params.set(k,next[k])});router.push(`${pathname}${params.size?`?${params}`:""}`,{scroll:false});setVisible(4);track("property_search",{filters:[...params.keys()].length})},[filters,pathname,router]);
 const set=(key:keyof Filters,value:string)=>setFilters(c=>({...c,[key]:value}));
 const municipalities=React.useMemo(()=>[...new Set(properties.map(p=>p.municipality).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt")),[properties]);
 const parishes=React.useMemo(()=>[...new Set(properties.filter(p=>!filters.concelho||p.municipality===filters.concelho).map(p=>p.parish).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt")),[properties,filters.concelho]);
 const filtered=React.useMemo(()=>{const q=clean(filters.q);let rows=properties.filter(p=>{const text=clean(`${p.title} ${p.reference} ${p.parish} ${p.municipality} ${p.type} ${p.typology??""} ${p.description??""}`);return(!q||text.includes(q))&&(!filters.operacao||p.operation===(filters.operacao==="comprar"?"venda":"arrendamento"))&&(!filters.concelho||clean(p.municipality)===clean(filters.concelho))&&(!filters.freguesia||clean(p.parish)===clean(filters.freguesia))&&(!filters.tipo||p.type===filters.tipo)&&(!filters.tipologia||p.typology===filters.tipologia)&&(!filters.precoMin||p.price>=Number(filters.precoMin))&&(!filters.precoMax||p.price<=Number(filters.precoMax))&&(!filters.quartos||p.beds>=Number(filters.quartos))&&(!filters.banhos||p.baths>=Number(filters.banhos))&&(!filters.areaMin||p.area>=Number(filters.areaMin))&&(!filters.referencia||clean(p.reference).includes(clean(filters.referencia)))&&(!filters.signature||p.isSignature)&&(!filters.empreendimento||p.isDevelopment)&&(!filters.estado||p.status===filters.estado)&&(!filters.caracteristica||clean(`${p.shortDescription??""} ${p.description??""}`).includes(clean(filters.caracteristica)))});const scores=propertyScores(rows);rows=[...rows].sort((a,b)=>filters.ordem==="preco-asc"?a.price-b.price:filters.ordem==="preco-desc"?b.price-a.price:filters.ordem==="qualidade"?(scores.get(b.id)?.quality??0)-(scores.get(a.id)?.quality??0):Date.parse(b.listedAt||"1970-01-01")-Date.parse(a.listedAt||"1970-01-01"));if(filters.concelho){const winner=selectMunicipalityWinner(rows,filters.concelho,config.rotation);if(winner)rows=[winner,...rows.filter(p=>p.id!==winner.id)]}return rows},[properties,filters,config.rotation]);
 const hero=selectGeneralHero(properties,config.rotation); const counts=new globalThis.Map(municipalities.map(n=>[n,properties.filter(p=>p.municipality===n).length]));const top=(config.municipalities?.filter(n=>counts.has(n))??[]).slice(0,3);[...municipalities].sort((a,b)=>(counts.get(b)??0)-(counts.get(a)??0)).forEach(n=>{if(top.length<3&&!top.includes(n))top.push(n)});
 const promo=config.promo;const showPromo=promo?.active!==false&&(!promo?.startsAt||Date.parse(promo.startsAt)<=Date.now())&&(!promo?.endsAt||Date.parse(promo.endsAt)>=Date.now());
 return <main className="mx-auto max-w-[1180px] px-5 pb-16 pt-5 sm:px-7 lg:px-8"><nav aria-label="Breadcrumb" className="text-xs text-[#65758a] sm:text-sm"><Link href="/">Início</Link> <span className="px-1">/</span> Imóveis</nav>
 <section className="mt-3"><h1 className="font-display text-[2rem] font-bold leading-tight tracking-[-.035em] sm:text-5xl">{config.title}</h1><p className="mt-1 text-base text-[#64748b] sm:text-lg">{config.intro}</p><form onSubmit={e=>{e.preventDefault();apply()}} className="mt-4 sm:mt-6"><div className="flex gap-2.5"><label className="relative flex min-h-12 flex-1 items-center rounded-2xl bg-white shadow-[0_8px_28px_rgba(13,59,102,.09)] sm:min-h-14"><Search className="ml-4 size-5"/><span className="sr-only">Localização, referência ou palavra-chave</span><input value={filters.q} onChange={e=>set("q",e.target.value)} placeholder="Localização, referência ou palavra-chave" className="h-12 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none sm:h-14 sm:px-4 sm:text-base"/></label><button type="button" aria-label="Filtros avançados" aria-expanded={advanced} onClick={()=>setAdvanced(v=>!v)} className="grid size-12 shrink-0 place-items-center rounded-2xl bg-white shadow-[0_8px_28px_rgba(13,59,102,.09)] sm:size-14"><SlidersHorizontal className="size-5"/></button><button className="hidden min-h-14 rounded-2xl bg-[#A31621] px-6 font-semibold text-white lg:block">Pesquisar</button></div>{advanced&&<Advanced filters={filters} set={set} municipalities={municipalities} parishes={parishes} close={()=>setAdvanced(false)} clear={()=>{const empty=readFilters(new URLSearchParams());setFilters(empty);router.push(pathname)}}/>}</form></section>
 {hero&&<Hero property={hero} remember={remember}/>} {top.length>0&&<section className="mt-7 sm:mt-10"><p className="eyebrow">Destinos mais procurados</p><h2 className="section-title">Descubra por concelho</h2><div className="-mx-5 mt-3 flex snap-x gap-2.5 overflow-x-auto px-5 pb-2 [scrollbar-width:none] sm:mx-0 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-3 sm:px-0">{top.map(name=><Municipality key={name} name={name} image={config.municipalityPhotos?.[clean(name)]||properties.find(p=>p.municipality===name)?.image||""} alt={config.municipalityAlt?.[clean(name)]||`Imóveis em ${name}`}/>)}</div><div className="mt-2 flex justify-center gap-1.5 sm:hidden"><span className="h-1.5 w-7 rounded-full bg-[#A31621]"/><span className="size-1.5 rounded-full bg-slate-300"/><span className="size-1.5 rounded-full bg-slate-300"/></div></section>}
 {showPromo&&<Link href={promo?.href||"/avaliacao-imovel"} onClick={()=>track("property_promo_click")} className="relative mt-5 block min-h-36 overflow-hidden rounded-2xl bg-[#0D3B66] text-white sm:mt-9 sm:min-h-48"><img src={promo?.image} alt={promo?.alt||""} className="absolute inset-0 size-full object-cover object-right"/><div className="absolute inset-0 bg-gradient-to-r from-[#07335b] via-[#0D3B66]/90 to-[#0D3B66]/5"/><div className="relative max-w-xl p-5 sm:p-9"><h2 className="font-display text-2xl font-bold sm:text-4xl">{promo?.title}</h2><p className="mt-1 text-sm text-white/90 sm:mt-2 sm:text-base">{promo?.text}</p><span className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#0D3B66] sm:mt-6 sm:min-h-11 sm:px-5 sm:text-base">{promo?.label}<ArrowRight className="size-4"/></span></div></Link>}
 <AlertBlock config={config} filters={filters} set={set} municipalities={municipalities} open={()=>setAlertOpen(true)}/>
 <section className="mt-7 sm:mt-12" id="todos"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow">Todos os imóveis</p><h2 className="section-title">Casas para descobrir</h2><p aria-live="polite" className="sr-only">{filtered.length} {filtered.length===1?"imóvel":"imóveis"}</p></div><label className="shrink-0 text-[10px] sm:text-sm">Ordenar: <select value={filters.ordem} onChange={e=>{const n={...filters,ordem:e.target.value};setFilters(n);apply(n)}} className="min-h-10 max-w-28 bg-transparent font-semibold sm:min-h-11 sm:max-w-none"><option value="recentes">Mais recentes</option><option value="preco-asc">Preço mais baixo</option><option value="preco-desc">Preço mais alto</option><option value="qualidade">Qualidade</option></select></label></div><div className="mt-3 flex items-center gap-1.5 overflow-x-auto pb-1 [scrollbar-width:none] sm:mt-5 sm:flex-wrap sm:gap-2"><Quick active={filters.operacao==="comprar"} onClick={()=>{const n={...filters,operacao:"comprar"};setFilters(n);apply(n)}}>Comprar</Quick><Quick active={filters.operacao==="arrendar"} onClick={()=>{const n={...filters,operacao:"arrendar"};setFilters(n);apply(n)}}>Arrendar</Quick><Quick onClick={()=>setAdvanced(true)}>Tipologia <ChevronDown className="size-3"/></Quick><Quick onClick={()=>setAdvanced(true)}>Preço <ChevronDown className="size-3"/></Quick><Quick onClick={()=>setAdvanced(true)}>Mais filtros <ListFilter className="size-3"/></Quick><span className="flex-1"/><div className="flex shrink-0 rounded-xl bg-white p-1 shadow-sm"><button aria-label="Vista em grelha" onClick={()=>{setView("grid");track("property_view_toggle",{view:"grid"})}} className={`grid size-10 place-items-center rounded-lg sm:size-11 ${view==="grid"?"bg-[#0D3B66] text-white":""}`}><Grid2X2 className="size-4"/></button><button aria-label="Vista no mapa" onClick={()=>{setView("map");track("property_view_toggle",{view:"map"})}} className={`grid size-10 place-items-center rounded-lg sm:size-11 ${view==="map"?"bg-[#0D3B66] text-white":""}`}><Map className="size-4"/></button></div></div>{filtered.length===0?<Empty/>:view==="grid"?<div className="mt-3 grid grid-cols-2 gap-2.5 sm:mt-6 sm:gap-4 lg:grid-cols-3 xl:grid-cols-4">{filtered.slice(0,visible).map(p=><Card key={p.id} property={p} remember={remember}/>)}</div>:<PropertyMap properties={filtered.slice(0,visible)} remember={remember}/>} {visible<filtered.length&&<button onClick={()=>{setVisible(v=>v+8);track("property_load_more")}} className="mt-4 min-h-11 w-full rounded-xl border-2 border-[#A31621] text-sm font-bold text-[#A31621] sm:mt-7 sm:min-h-12 sm:text-base">Ver mais imóveis <ArrowRight className="ml-2 inline size-4"/></button>}</section>{alertOpen&&<AlertDialog filters={filters} close={()=>setAlertOpen(false)}/>}</main>
}

function Advanced({filters,set,municipalities,parishes,close,clear}:{filters:Filters;set:(k:keyof Filters,v:string)=>void;municipalities:string[];parishes:string[];close:()=>void;clear:()=>void}){return <div className="mt-4 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><b>Filtros avançados</b><button type="button" onClick={close} className="grid size-11 place-items-center"><X/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="Operação" value={filters.operacao} change={v=>set("operacao",v)} options={[["comprar","Comprar"],["arrendar","Arrendar"]]}/><Select label="Concelho" value={filters.concelho} change={v=>set("concelho",v)} options={municipalities.map(v=>[v,v])}/><Select label="Freguesia" value={filters.freguesia} change={v=>set("freguesia",v)} options={parishes.map(v=>[v,v])}/><Select label="Tipo de imóvel" value={filters.tipo} change={v=>set("tipo",v)} options={["Apartamento","Moradia","Terreno","Loja","Escritório"].map(v=>[v,v])}/><Select label="Tipologia" value={filters.tipologia} change={v=>set("tipologia",v)} options={["T0","T1","T2","T3","T4","T5"].map(v=>[v,v])}/><Input label="Preço mínimo" value={filters.precoMin} change={v=>set("precoMin",v)} numeric/><Input label="Preço máximo" value={filters.precoMax} change={v=>set("precoMax",v)} numeric/><Input label="Área mínima (m²)" value={filters.areaMin} change={v=>set("areaMin",v)} numeric/><Select label="Quartos" value={filters.quartos} change={v=>set("quartos",v)} options={[1,2,3,4,5].map(v=>[String(v),`${v}+`])}/><Select label="Casas de banho" value={filters.banhos} change={v=>set("banhos",v)} options={[1,2,3,4].map(v=>[String(v),`${v}+`])}/><Input label="Características" value={filters.caracteristica} change={v=>set("caracteristica",v)}/><Input label="Referência" value={filters.referencia} change={v=>set("referencia",v)}/><Check label="HousePro Signature" checked={!!filters.signature} change={v=>set("signature",v?"1":"")}/><Check label="Empreendimentos" checked={!!filters.empreendimento} change={v=>set("empreendimento",v?"1":"")}/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={clear} className="min-h-11 px-4 font-semibold">Limpar tudo</button><button className="min-h-11 rounded-xl bg-[#A31621] px-6 font-semibold text-white">Ver resultados</button></div></div>}
function Hero({property,remember}:{property:Property;remember:()=>void}){return <section className="relative mt-4 overflow-hidden rounded-2xl bg-white shadow-[0_16px_42px_rgba(13,59,102,.18)] sm:mt-6"><div className="relative aspect-[16/10] w-full sm:aspect-[2/1]"><img src={property.image} alt={`${property.type} em ${property.municipality}`} className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#071d37]/35 via-transparent to-transparent"/><span className="absolute left-3 top-3 rounded-full bg-[#0D3B66] px-3 py-1.5 text-[10px] font-bold text-white sm:left-4 sm:top-4 sm:text-xs">IMÓVEL EM DESTAQUE</span><div className="absolute right-3 top-3 sm:right-4 sm:top-4"><FavoriteButton propertyId={property.id}/></div><span className="absolute bottom-6 right-3 rounded-full bg-[#071d37]/80 px-2.5 py-1 text-xs text-white sm:bottom-7">1 / {Math.max(1,property.gallery?.length??1)}</span></div><div className="relative z-10 -mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 rounded-t-2xl bg-white p-4 sm:-mt-5 sm:p-5"><div className="min-w-0"><h2 className="font-display text-lg font-bold leading-tight sm:text-2xl">{property.title}</h2><Location p={property}/><p className="mt-1 text-xl font-bold sm:mt-2 sm:text-2xl">{formatPrice(property)}</p><Specs p={property}/></div><Link onClick={remember} href={`/imovel/${property.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#A31621] px-4 text-sm font-bold text-white sm:min-h-12 sm:px-7 sm:text-base">Ver imóvel <ArrowRight className="size-4"/></Link></div></section>}
function Municipality({name,image,alt}:{name:string;image:string;alt:string}){return <Link href={`/imoveis?concelho=${encodeURIComponent(name)}`} onClick={()=>track("property_municipality_click",{municipality:name})} className="relative h-44 w-[43vw] max-w-[250px] shrink-0 snap-start overflow-hidden rounded-xl bg-[#0D3B66] text-white sm:h-52 sm:w-auto sm:max-w-none sm:rounded-2xl"><img src={image} alt={alt} className="size-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#082e55]/90 via-transparent"/><div className="absolute inset-x-0 bottom-0 p-3 sm:p-5"><h3 className="font-display text-lg font-bold sm:text-2xl">{name}</h3><span className="inline-flex items-center gap-1 text-xs sm:gap-2 sm:text-sm">Explorar <ArrowRight className="size-4"/></span></div></Link>}
function AlertBlock({config,filters,set,municipalities,open}:{config:PropertyHubConfig;filters:Filters;set:(k:keyof Filters,v:string)=>void;municipalities:string[];open:()=>void}){return <section className="mt-3 rounded-2xl border bg-white p-4 shadow-sm sm:mt-5 sm:p-5"><div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#edf4fa]"><Bell className="size-5"/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="font-display text-base font-bold sm:text-xl">{config.alertTitle}</h2><span className="hidden text-[10px] text-[#607086] sm:block">Pode cancelar quando quiser</span></div><p className="mt-0.5 text-xs leading-snug text-[#607086] sm:text-sm">{config.alertText}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2 sm:mt-5 sm:grid-cols-4"><Select label="Zona" hide value={filters.concelho} change={v=>set("concelho",v)} options={municipalities.map(v=>[v,v])}/><Select label="Preço" hide value={filters.precoMax} change={v=>set("precoMax",v)} options={[["250000","Até 250 000 €"],["500000","Até 500 000 €"],["1000000","Até 1 000 000 €"]]}/><Select label="Tipologia" hide value={filters.tipologia} change={v=>set("tipologia",v)} options={["T0","T1","T2","T3","T4","T5"].map(v=>[v,v])}/><button onClick={open} className="min-h-11 rounded-xl bg-[#A31621] px-3 text-sm font-bold text-white sm:min-h-12 sm:px-5">Criar alerta <ArrowRight className="ml-1 inline size-4"/></button></div><Link href="/cliente/comprador" className="mt-2 inline-flex text-xs font-semibold text-[#397ca8] underline sm:mt-4 sm:text-sm">Pesquisa personalizada <ArrowRight className="ml-1 size-4"/></Link></section>}
function Card({property,remember}:{property:Property;remember:()=>void}){return <article className="min-w-0 overflow-hidden rounded-xl bg-white shadow-[0_5px_18px_rgba(13,59,102,.09)] sm:rounded-2xl"><div className="relative aspect-[4/3]"><Link href={`/imovel/${property.id}`} onClick={remember} className="block size-full"><img src={property.image} alt={`${property.type} em ${property.parish}, ${property.municipality}`} loading="lazy" className="size-full object-cover"/></Link><div className="absolute right-2 top-2 sm:right-3 sm:top-3"><FavoriteButton propertyId={property.id}/></div>{property.isSignature&&<span className="absolute left-2 top-2 rounded-full bg-[#0D3B66] px-2 py-1 text-[8px] font-bold text-white sm:left-3 sm:top-3 sm:text-[10px]">SIGNATURE</span>}</div><div className="p-2.5 sm:p-4"><h3 className="line-clamp-1 font-display text-sm font-bold sm:text-lg"><Link href={`/imovel/${property.id}`} onClick={remember}>{property.title}</Link></h3><Location p={property}/><p className="mt-1 text-base font-bold sm:mt-2 sm:text-xl">{formatPrice(property)}</p><Specs p={property}/></div></article>}
function Location({p}:{p:Property}){return <p className="mt-1 flex items-center gap-1 text-sm text-[#64748b]"><MapPin className="size-3.5"/>{p.parish}, {p.municipality}</p>}
function Specs({p}:{p:Property}){return <div className="mt-3 flex flex-wrap gap-3 border-t pt-3 text-xs text-[#607086]">{p.typology&&<b>{p.typology}</b>}<span><BedDouble className="mr-1 inline size-3.5"/>{p.beds}</span><span><Bath className="mr-1 inline size-3.5"/>{p.baths}</span><span><Maximize2 className="mr-1 inline size-3.5"/>{p.area} m²</span></div>}
function PropertyMap({properties,remember}:{properties:Property[];remember:()=>void}){const located=properties.filter(p=>p.lat!=null&&p.lng!=null);return <div className="relative mt-6 min-h-[520px] overflow-hidden rounded-2xl bg-[#dceaf2] p-5"><div className="relative grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{located.map(p=><Link onClick={remember} key={p.id} href={`/imovel/${p.id}`} className="rounded-xl bg-white p-3 shadow"><b>{formatPrice(p)}</b><span className="block truncate text-sm">{p.title}</span><span className="text-xs">{p.municipality}</span></Link>)}</div>{!located.length&&<div className="relative grid min-h-[480px] place-items-center text-center"><div><MapPin className="mx-auto size-9"/><b className="mt-3 block">Localização protegida</b><p className="mt-1 max-w-sm text-sm">Os marcadores aparecem quando existem coordenadas autorizadas.</p></div></div>}</div>}
function Empty(){return <div className="mt-6 rounded-2xl border border-dashed bg-white p-12 text-center"><Search className="mx-auto size-8"/><h3 className="mt-4 font-display text-2xl font-bold">Sem resultados para estes filtros</h3><p className="mt-2 text-sm">Altere os critérios ou crie um alerta.</p></div>}
function Select({label,value,change,options,hide=false}:{label:string;value:string;change:(v:string)=>void;options:string[][];hide?:boolean}){return <label className="text-xs font-semibold">{!hide&&label}<span className="relative mt-1 block"><select aria-label={label} value={value} onChange={e=>change(e.target.value)} className="min-h-12 w-full appearance-none rounded-xl border bg-white px-3 pr-9 text-sm font-normal"><option value="">{label}</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-4 size-4"/></span></label>}
function Input({label,value,change,numeric=false}:{label:string;value:string;change:(v:string)=>void;numeric?:boolean}){return <label className="text-xs font-semibold">{label}<input value={value} inputMode={numeric?"numeric":undefined} onChange={e=>change(numeric?e.target.value.replace(/\D/g,""):e.target.value)} className="mt-1 min-h-12 w-full rounded-xl border px-3 text-sm font-normal"/></label>}
function Check({label,checked,change}:{label:string;checked:boolean;change:(v:boolean)=>void}){return <label className="flex min-h-12 items-center gap-3 rounded-xl border px-3 text-sm"><input type="checkbox" checked={checked} onChange={e=>change(e.target.checked)} className="size-4 accent-[#A31621]"/>{label}</label>}
function Quick({children,active=false,onClick}:{children:React.ReactNode;active?:boolean;onClick:()=>void}){return <button onClick={onClick} className={`inline-flex min-h-11 items-center gap-1 rounded-full px-4 text-sm font-semibold ${active?"bg-[#0D3B66] text-white":"border bg-white"}`}>{children}</button>}
function AlertDialog({filters,close}:{filters:Filters;close:()=>void}){const [status,setStatus]=React.useState("");const [saved,setSaved]=React.useState<{id:string;email:string}|null>(null);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("A guardar…");const fd=new FormData(e.currentTarget);const email=String(fd.get("email")||"");const res=await fetch("/api/property-alert",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,phone:fd.get("phone"),consent:fd.get("consent")==="on",marketingConsent:fd.get("marketing")==="on",criteria:filters,pageUrl:location.href,referrerUrl:document.referrer,utm:Object.fromEntries(new URLSearchParams(location.search))})});const data=await res.json().catch(()=>({}));setStatus(res.ok?"Alerta criado com sucesso.":"Não foi possível criar o alerta. Confirme os dados.");if(res.ok){setSaved({id:data.id,email});track("property_alert_created")}}async function cancel(){if(!saved)return;setStatus("A cancelar…");const res=await fetch("/api/property-alert",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify(saved)});setStatus(res.ok?"Alerta cancelado.":"Não foi possível cancelar o alerta.");if(res.ok)setSaved(null)}return <div className="fixed inset-0 z-[80] grid place-items-center bg-[#071d37]/70 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><div><h2 className="font-display text-2xl font-bold">Criar alerta de imóveis</h2><p className="text-sm">Enviaremos apenas imóveis compatíveis.</p></div><button type="button" onClick={close} aria-label="Fechar" className="grid size-11 place-items-center"><X/></button></div><div className="mt-5 grid gap-3"><label className="text-xs font-semibold">E-mail<input required type="email" name="email" className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label className="text-xs font-semibold">Telefone (opcional)<input name="phone" className="mt-1 min-h-12 w-full rounded-xl border px-3"/></label><label className="flex gap-2 text-xs"><input required name="consent" type="checkbox" className="size-4"/>Autorizo o tratamento dos dados para gerir este alerta.</label><label className="flex gap-2 text-xs"><input name="marketing" type="checkbox" className="size-4"/>Quero receber novidades HousePro (opcional).</label><button className="min-h-12 rounded-xl bg-[#A31621] font-bold text-white">Criar alerta</button>{saved&&<button type="button" onClick={cancel} className="min-h-11 rounded-xl border font-semibold">Cancelar este alerta</button>}{status&&<p role="status" className="text-sm font-semibold">{status}</p>}</div></form></div>}
